//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.dataservice.ISteamApps;

import android.app.Activity;
import android.content.Context;
import android.widget.TextView;
import studio.lc.dotaanalysis.R.id;
import studio.lc.dotaanalysis.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class AppItem_
    extends AppItem
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public AppItem_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        appname = ((TextView) findViewById(id.appname));
        appid = ((TextView) findViewById(id.appid));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.lv_app, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static AppItem build(Context context) {
        AppItem_ instance = new AppItem_(context);
        instance.onFinishInflate();
        return instance;
    }

}
