//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.dataservice.ISteamApps;

import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;
import studio.lc.dotaanalysis.dataservice.ISteamApps.dataBean.Applist;

public class ISteamAppsDP_
    implements ISteamAppsDP
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public ISteamAppsDP_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
        rootUrl = "http://api.steampowered.com/ISteamApps";
    }

    @Override
    public Applist GetAppList() {
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("/GetAppList/v2"), HttpMethod.GET, requestEntity, Applist.class).getBody();
    }

}
