//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import studio.lc.dotaanalysis.R.id;
import studio.lc.dotaanalysis.R.layout;
import studio.lc.dotaanalysis.dataservice.ISteamApps.AppAdapter_;
import studio.lc.dotaanalysis.dataservice.ISteamApps.ISteamAppsDP_;

public final class ApplistActivity_
    extends ApplistActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.apps_activity);
    }

    private void init_(Bundle savedInstanceState) {
        iSteamApps = new ISteamAppsDP_();
        appadapter = AppAdapter_.getInstance_(this);
    }

    private void afterSetContentView_() {
        applist = ((ListView) findViewById(id.applist));
        ((AppAdapter_) appadapter).afterSetContentView_();
        setview();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ApplistActivity_.IntentBuilder_ intent(Context context) {
        return new ApplistActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ApplistActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ApplistActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
