//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis;

import java.sql.SQLException;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.GridView;
import com.j256.ormlite.android.apptools.OpenHelperManager;
import com.j256.ormlite.dao.DaoManager;
import com.j256.ormlite.support.ConnectionSource;
import studio.lc.dotaanalysis.R.id;
import studio.lc.dotaanalysis.R.layout;
import studio.lc.dotaanalysis.dataservice.DatabaseHelper;
import studio.lc.dotaanalysis.dataservice.IDota2.HeroAdapter_;
import studio.lc.dotaanalysis.dataservice.IDota2.dataBean.Hero;

public final class HerosActivity_
    extends HerosActivity
{

    private ConnectionSource connectionSource_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.heros_activity);
    }

    private void init_(Bundle savedInstanceState) {
        connectionSource_ = OpenHelperManager.getHelper(this, DatabaseHelper.class).getConnectionSource();
        try {
            herodao = DaoManager.createDao(connectionSource_, Hero.class);
        } catch (SQLException e) {
            Log.e("HerosActivity_", "Could not create DAO", e);
        }
        adapter = HeroAdapter_.getInstance_(this);
    }

    private void afterSetContentView_() {
        heros = ((GridView) findViewById(id.heros));
        ((HeroAdapter_) adapter).afterSetContentView_();
        setdata();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static HerosActivity_.IntentBuilder_ intent(Context context) {
        return new HerosActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, HerosActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public HerosActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
