//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.googlecode.androidannotations.api.sharedpreferences.EditorHelper;
import com.googlecode.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefEditorField;
import com.googlecode.androidannotations.api.sharedpreferences.StringPrefField;

public final class SteamPrefs_
    extends SharedPreferencesHelper
{


    public SteamPrefs_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
    }

    public SteamPrefs_.SteamPrefsEditor_ edit() {
        return new SteamPrefs_.SteamPrefsEditor_(getSharedPreferences());
    }

    public StringPrefField steamId() {
        return stringField("steamId", "");
    }

    public final static class SteamPrefsEditor_
        extends EditorHelper<SteamPrefs_.SteamPrefsEditor_>
    {


        SteamPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public StringPrefEditorField<SteamPrefs_.SteamPrefsEditor_> steamId() {
            return stringField("steamId");
        }

    }

}
