//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.dataservice.IDota2;

import java.util.HashMap;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.converter.json.MappingJacksonHttpMessageConverter;
import org.springframework.web.client.RestTemplate;
import studio.lc.dotaanalysis.dataservice.IDota2.dataBean.HerosResult;

public class IDotaHeroDP_
    implements IDotaHeroDP
{

    private RestTemplate restTemplate;
    private String rootUrl;

    public IDotaHeroDP_() {
        restTemplate = new RestTemplate();
        restTemplate.getMessageConverters().add(new MappingJacksonHttpMessageConverter());
        rootUrl = "http://api.steampowered.com/IEconDOTA2_";
    }

    @Override
    public HerosResult GetHeroes(int id, String language) {
        HashMap<String, Object> urlVariables = new HashMap<String, Object>();
        urlVariables.put("id", id);
        urlVariables.put("language", language);
        HttpHeaders httpHeaders = new HttpHeaders();
        HttpEntity<Object> requestEntity = new HttpEntity<Object>(httpHeaders);
        return restTemplate.exchange(rootUrl.concat("{id}/GetHeroes/v1?key=D9F210C67C52FCE7C25B86441C9ED2EA&language={language}"), HttpMethod.GET, requestEntity, HerosResult.class, urlVariables).getBody();
    }

}
