//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.dataservice.IDotaMatch;

import android.app.Activity;
import android.content.Context;
import android.widget.GridView;
import android.widget.TextView;
import studio.lc.dotaanalysis.R.id;
import studio.lc.dotaanalysis.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class MatchItem_
    extends MatchItem
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public MatchItem_(Context context) {
        super(context);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        playerAdapter = PlayerAdapter_.getInstance_(context_);
    }

    private void afterSetContentView_() {
        matchid = ((TextView) findViewById(id.matchid));
        heros = ((GridView) findViewById(id.heros));
        ((PlayerAdapter_) playerAdapter).afterSetContentView_();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.lv_match, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static MatchItem build(Context context) {
        MatchItem_ instance = new MatchItem_(context);
        instance.onFinishInflate();
        return instance;
    }

}
