//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.dataservice.IDotaMatch;

import android.app.Activity;
import android.content.Context;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import studio.lc.dotaanalysis.BaseActivity;

public final class MatchAdapter_
    extends MatchAdapter
{

    private Context context_;
    private Handler handler_ = new Handler();

    private MatchAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public void afterSetContentView_() {
        if (!(context_ instanceof Activity)) {
            return ;
        }
        ((MatchFinderImpl_) matchFinder).afterSetContentView_();
    }

    /**
     * You should check that context is an activity before calling this method
     * 
     */
    public View findViewById(int id) {
        Activity activity_ = ((Activity) context_);
        return activity_.findViewById(id);
    }

    @SuppressWarnings("all")
    private void init_() {
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        if (context_ instanceof BaseActivity) {
            context = ((BaseActivity) context_);
        }
        matchFinder = MatchFinderImpl_.getInstance_(context_);
        initAdapter();
    }

    public static MatchAdapter_ getInstance_(Context context) {
        return new MatchAdapter_(context);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @Override
    public void updateui() {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    MatchAdapter_.super.updateui();
                } catch (RuntimeException e) {
                    Log.e("MatchAdapter_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

}
