//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package studio.lc.dotaanalysis.customwidget;

import android.app.Activity;
import android.content.Context;
import android.util.AttributeSet;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.ImageView;
import android.widget.TextView;
import studio.lc.dotaanalysis.R.id;
import studio.lc.dotaanalysis.R.layout;
import studio.lc.dotaanalysis.SteamPrefs_;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class ProfileItem_
    extends ProfileItem
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public ProfileItem_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
        prefs = new SteamPrefs_(context_);
    }

    private void afterSetContentView_() {
        avatar = ((ImageView) findViewById(id.avatar));
        personaname = ((TextView) findViewById(id.personaname));
        status = ((TextView) findViewById(id.status));
        friendlattime = ((TextView) findViewById(id.friendlattime));
        {
            View view = findViewById(id.avatar);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProfileItem_.this.avatarClicked();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.logout);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ProfileItem_.this.logout();
                    }

                }
                );
            }
        }
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.profile_layout, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static ProfileItem build(Context context, AttributeSet attrs) {
        ProfileItem_ instance = new ProfileItem_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

}
